language:
  - node.js

script:
  - echo "Deploying!"

install:
  - npm install -g firebase-tools

after_success:
  - firebase deploy --token 1//0600xNcvpe_QfCgYIARAAGAYSNwF-L9IrT5f9qMmiiBvbue-MLDiVPBHmk0ox81yy3b6rgIACzoEeg29VQgufc_CPZjjZvhBILlE